### ISSUE TITLE
Good code

### ISSUE THREAD

**Issue by suchy2020** [Airkek/Discord-Nitro-BruteForce#13]
`{"code": "T9QqM3NAKTGQuWNvKNDBNy9Y", "sku_id": "521847234246082599", "application_id": "521842831262875670", "uses": 0, "max_uses": 1, "expires_at": "2020-11-28T00:00:00+00:00", "redeemed": false, "flags": 3, "store_listing": {"id": "521848044908576803", "summary": " ", "sku": {"id": "521847234246082599", "type": 5, "dependent_sku_id": null, "application_id": "521842831262875670", "manifest_labels": null, "access_type": 1, "name": "Nitro", "features": [], "release_date": null, "premium": null, "slug": "nitro", "flags": 4, "show_age_gate": false}, "thumbnail": {"id": "633877574094684160", "size": 148981, "mime_type": "image/png", "width": 556, "height": 316}}, "subscription_plan": {"id": "511651880837840896", "name": "Nitro Monthly", "interval": 1, "interval_count": 1, "tax_inclusive": true, "sku_id": "521847234246082599", "currency": "usd", "price": 999}}`

https://discordapp.com/api/v8/entitlements/gift-codes/T9QqM3NAKTGQuWNvKNDBNy9Y?with_application=false&with_subscription_plan=true

btw i got this from xbox game pass

**Comment by suchy2020** [comment]
used btw xd

**Comment by Airkek** [comment]
can you provide raw stream of this request?

**Comment by Airkek** [comment]
![image](https://user-images.githubusercontent.com/45855057/91900764-d70f0200-eca7-11ea-8fb4-0ef08b10c89b.png)

**Comment by suchy2020** [comment]
How to get this on chrome?

**Comment by suchy2020** [comment]
![image](https://user-images.githubusercontent.com/34921955/91902729-729d7400-eca2-11ea-8f6f-817f07e4aeb2.png)
![image](https://user-images.githubusercontent.com/34921955/91902765-7d580900-eca2-11ea-8815-377378b32137.png)

**Comment by Airkek** [comment]
thx

**Comment by Airkek** [comment]
Raw stream:

**Comment by Airkek** [comment]
`{
   "code":"T9QqM3NAKTGQuWNvKNDBNy9Y",
   "sku_id":"521847234246082599",
   "application_id":"521842831262875670",
   "uses":1,
   "max_uses":1,
   "expires_at":"2020-11-28T00:00:00+00:00",
   "redeemed":false,
   "flags":3,
   "store_listing":{
      "id":"521848044908576803",
      "summary":" ",
      "sku":{
         "id":"521847234246082599",
         "type":5,
         "dependent_sku_id":null,
         "application_id":"521842831262875670",
         "manifest_labels":null,
         "access_type":1,
         "name":"Nitro",
         "features":[
            
         ],
         "release_date":null,
         "premium":null,
         "slug":"nitro",
         "flags":4,
         "show_age_gate":false
      },
      "thumbnail":{
         "id":"633877574094684160",
         "size":148981,
         "mime_type":"image/png",
         "width":556,
         "height":316
      }
   },
   "subscription_plan":{
      "id":"511651880837840896",
      "name":"Nitro Monthly",
      "interval":1,
      "interval_count":1,
      "tax_inclusive":true,
      "sku_id":"521847234246082599",
      "currency":"usd",
      "price":999
   }
}`

**Comment by Official-Husko** [comment]
Another good code

https://discord.com/api/v8/entitlements/gift-codes/6uJH3BRQHCdapZCZsewwKyB5

`{"code": "6uJH3BRQHCdapZCZsewwKyB5", "sku_id": "521847234246082599", "application_id": "521842831262875670", "uses": 1, "max_uses": 1, "expires_at": null, "redeemed": false, "store_listing": {"id": "521848044908576803", "summary": " ", "sku": {"id": "521847234246082599", "type": 5, "dependent_sku_id": null, "application_id": "521842831262875670", "manifest_labels": null, "access_type": 1, "name": "Nitro", "features": [], "release_date": null, "premium": null, "slug": "nitro", "flags": 4, "show_age_gate": false}, "thumbnail": {"id": "633877574094684160", "size": 148981, "mime_type": "image/png", "width": 556, "height": 316}}, "subscription_plan_id": "511651880837840896"}`
