### ISSUE TITLE
stupid question

### ISSUE THREAD

**Issue by entaytion** [Airkek/Discord-Nitro-BruteForce#14]
`C:\Users\001\Desktop\Discord-Nitro-BruteForce-master\Discord Nitro BruteForce\Discord Nitro BruteForce.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\001\Desktop\Discord-Nitro-BruteForce-master\Discord Nitro BruteForce\Discord Nitro BruteForce.csproj`

how to fix this, im **noob**, im using microsoft visual studio 2013

**Comment by suchy2020** [comment]
install 2019 or google it, i don't know how to repair this :c

**Comment by entaytion** [comment]
thx

**Comment by entaytion** [comment]
ok thx
