### ISSUE TITLE
Question about Functionality

### ISSUE THREAD

**Issue by Stahlhelm-TV** [Airkek/Discord-Nitro-BruteForce#7]
Can this checker already find Valid codes and display them or not?

I have seen that there is a line which says "I don't know status code of valid nitro gift" does that mean it can't tell if its valid or not or does it just give some statuscode?

**Comment by Airkek** [comment]
it displays all codes which status code is not invalid

**Comment by Stahlhelm-TV** [comment]
in the [good.txt](https://github.com/Airkek/Discord-Nitro-BruteForce/files/5095968/good.txt) i got 126 over the night and all had the statuscode 502 (Bad Gateway)
tried a few and none worked.

**Comment by Airkek** [comment]
it's xNet bag, will be fixed soon

**Comment by Stahlhelm-TV** [comment]
Ahh alright, Thanks for the answer

**Comment by suchy2020** [comment]
@Stahlhelm-TV how wtf i don't get any :ccccc

**Comment by suchy2020** [comment]
ahh ok i don't read all text c:

**Comment by suchy2020** [comment]
None worked
![image](https://user-images.githubusercontent.com/34921955/90743530-0862f780-e2d0-11ea-83e7-fd32979285e1.png)

**Comment by suchy2020** [comment]
![IMG_20200820_105158.jpg](https://user-images.githubusercontent.com/34921955/90749024-37c73380-e2d3-11ea-83bd-743693ff7985.jpg)

**Comment by Airkek** [comment]
it's just non-handled status code I use it for debug and to find status code of valid nitro
